cluster: 
    mkdir -p logs/{rule} &&
    sbatch --partitition={resources.partition} --cpus-per-task={threads} --mem={resources.mem_mb} --job-name=smk-{wildcards}-{rule} --output=logs/{rule}/{wildcards}-%j.out --time={resources.time}
default-resources:
    - partition=scavenger
    - mem_mb=1000
    - time="01:00:00"
use-conda: True
jobs: 10
rerun-incomplete: True
printshellcmds: True
